# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88368e7987c3cf99ad9925fede0e687624d3043b07022dae91dc210d82662178dd10c1e3ad917502277daeed12cc3454ba08dc1ccd54fccced619da816aeb036

test:
  secret_key_base: d495301c65e4d2c0cff4950b740f3f12679b780ef7c48209ae8c967e385ab745587111d185c531e3d1490a4cebad94e649b581c33b776cf3d8e0174f48978a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
